### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by SeppNel** [fuzzymannerz/lighttpd-link-php7#1]
Hi, I was using lighttpd-Link for a while now and decided to upgrade to this version with php but most of the time i can't start the server, and the very few times that it managed to start it just showed a "503 Service not Available" error when opening a .php file.
I followed every step in the installation guide, tried to run it with the default config and my custom config.

This is the error log when it can't start
![error log](https://user-images.githubusercontent.com/35899928/67494720-f990c180-f679-11e9-9f3a-707a2430ba6b.png)

And this is the serve.conf file:
![server conf](https://user-images.githubusercontent.com/35899928/67494881-470d2e80-f67a-11e9-80f5-056e5cd89dc1.png)
I don't think there's anything wrong with it since the problems still happens when using the default serve.conf but just in case.

**Comment by fuzzymannerz** [comment]
Hey there, I just completely removed everything from my Steam Link and tried it from fresh and I can't reproduce this error. I did see it once when I was testing though and it was due to symlinking of the library files in _/home/steam/php7.3.10/lib/_.

Are you sure you run the one time setup line before starting the server?
`chmod 755 /usr/local/sbin/lighttpd && chmod -R 755 /home/steam/php7.3.10/bin && chmod -R 755 /home/steam/php7.3.10/sbin && ldconfig`

If it doesn't work, try the uninstall script and then copy over the files again. :/

**Comment by SeppNel** [comment]
Reinstalled it but its the same. Error log: 

> 2019-10-24 16:58:05: (server.c.1412) server started (lighttpd/1.4.48) 
2019-10-24 16:58:05: (gw_backend.c.478) unlink /tmp/php-cgi.socket-0 after connect failed: Connection refused 
2019-10-24 16:58:05: (gw_backend.c.331) child exited: 127 unix:/tmp/php-cgi.socket-0 
2019-10-24 16:58:05: (gw_backend.c.609) gw-backend failed to start: /home/steam/php7.3.10/bin/armv7a-php-cgi 
2019-10-24 16:58:05: (gw_backend.c.611) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.  If this is PHP on Gentoo, add 'fastcgi' to the USE flags.  If this is PHP, try removing the bytecode caches for now and try again. 
2019-10-24 16:58:05: (gw_backend.c.1502) [ERROR]: spawning gw failed. 
2019-10-24 16:58:05: (server.c.1420) Configuration of plugins failed. Going down. 

Should the one time setup show anything on screen?

**Comment by fuzzymannerz** [comment]
No the setup will only show something if there was an error. Hmm, try running this one liner and let me know what happens when you try to run it after.

`ln -sf /home/steam/php7.3.10/lib/libxml2.so.2.9.9 /home/steam/php7.3.10/lib/libxml2.so && ln -sf /home/steam/php7.3.10/lib/libxml2.so.2.9.9 /home/steam/php7.3.10/lib/libxml2.so.2 && ldconfig`

**Comment by SeppNel** [comment]
Unfortunately that did nothing :/. But i noticed that if I restart the steam link i can consistenly get it to run but it still shows 503 error and keeps spamming the log with the same error from above until i kill it.

**Comment by fuzzymannerz** [comment]
Hmm very odd indeed!    

What's the outcome of `ls /tmp`?
Is there a load of "php-cgi.socket" files in there?

**Comment by SeppNel** [comment]
When running there was from "php-cgi.socket-0" to "php-cgi.socket-3" but when i killed it they got deleted, well most of the time, sometimes they get stuck there. Im doing a factory reset right now. I will let you know how that goes.

**Comment by SeppNel** [comment]
After finishing the factory reset, still the same issue.

**Comment by fuzzymannerz** [comment]
OK so I've factory reset my own Steam Link also (took ages) and yeah, now I'm in the same boat as you! haha :-1:     

~~On the plus side I know the actual cause of the error is the library file I mentioned "error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory" Problem is, it's in the right place and it's pointed to from the PHP config file so I'm gonna have to do a bit of digging around because I guess that somewhere between getting it working and packaging it up for upload I dunno what happened. :/~~

**EDIT: TEMPORARY FIX**
Running:    
`export LD_LIBRARY_PATH=/home/steam/php7.3.10/lib`    
before launching lighttpd will fix it temporarily but if you stop the service and log out/turn off the device you will need to do it again. Working on a better fix,

**Comment by fuzzymannerz** [comment]
https://github.com/fuzzymannerz/lighttpd-link-php7/commit/6453aeb1d5ac61fd58aa538e7062185de2b1d192
